/* fetch-fonts.mjs — one-off utility to self-host Fraunces.
 *
 * Downloads the woff2 files Google Fonts serves for our axes and writes:
 *   - public/fonts/fraunces-<n>.woff2   (the binaries)
 *   - src/styles/fonts.css              (@font-face rules pointing at /fonts/…)
 *
 * Re-run to refresh: node scripts/fetch-fonts.mjs
 * (Keeps Google's subsetting + unicode-range, just rehosts the files locally.)
 */

import { writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const FONT_DIR = join(ROOT, "public", "fonts");
const CSS_OUT = join(ROOT, "src", "styles", "fonts.css");

const CSS_URL =
  "https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,400;1,9..144,400&display=swap";
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36";

const css = await (await fetch(CSS_URL, { headers: { "User-Agent": UA } })).text();

await mkdir(FONT_DIR, { recursive: true });

const urls = [...css.matchAll(/url\((https:\/\/[^)]+\.woff2)\)/g)].map((m) => m[1]);
if (!urls.length) throw new Error("No woff2 URLs found in Google CSS response.");

let localCss = `/* fonts.css — self-hosted Fraunces (generated by scripts/fetch-fonts.mjs).
   Do not edit by hand; re-run the script to refresh. */\n\n` + css;

let i = 0;
for (const url of urls) {
  const name = `fraunces-${i}.woff2`;
  const buf = Buffer.from(await (await fetch(url)).arrayBuffer());
  await writeFile(join(FONT_DIR, name), buf);
  localCss = localCss.replaceAll(url, `/fonts/${name}`);
  console.log(`↓ ${name}  (${(buf.length / 1024).toFixed(1)} kB)`);
  i++;
}

await writeFile(CSS_OUT, localCss, "utf8");
console.log(`✓ wrote ${i} woff2 files + src/styles/fonts.css`);
